<?php
$webinarData = $block->getWebinarData();
?>

<?= /* @noEscape */ $block->getCmsContent() ?>


<!-- Initiate the countdown timer -->
<script type="text/x-magento-init">
    {
        "*": {
            "showtimer" : {
                "webinarId": "<?= /* @escapeNotVerified */ $webinarData->getId() ?>",
                "webinarDate": "<?= /* @escapeNotVerified */ $webinarData->getDate() ?>",
                "countdown": ".countdown"
            }
        }
    }
</script>